%%writefile .github/workflows/pipeline.yml
name: MLOps Pipeline for Vehicle Predictive Maintenance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Job to register data
  register-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r predictive_maintenance/deployment/requirements.txt
      - name: Run data registration script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python predictive_maintenance/model_building/data_register.py

  # Job for data preparation
  data-prep:
    needs: register-data # Depends on data-registration job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r predictive_maintenance/deployment/requirements.txt
      - name: Run data preparation script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python predictive_maintenance/model_building/prep.py

  # Job for model training and registration
  model-training:
    needs: data-prep # Depends on data-prep job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r predictive_maintenance/deployment/requirements.txt
      - name: Run model training script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python predictive_maintenance/model_building/train.py

  # Job for deployment hosting
  hosting:
    needs: model-training # Depends on model-training job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install -r predictive_maintenance/deployment/requirements.txt
      - name: Run hosting script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python predictive_maintenance/hosting/hosting.py
